spring.application.name=demo

# DB connection
spring.datasource.url=jdbc:mysql://localhost:3306/demo
spring.datasource.username=
spring.datasource.password=

# Hibernate will use this dialect to create appropriate SQL statements with respect to DB
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# tells hibernate to create/update the DB as per the JPA entities automatically
spring.jpa.hibernate.ddl-auto=update